### ISSUE TITLE
getUserData NotImplementedError

### ISSUE THREAD

**Issue by wayfarerboy** [vmg/SkeletonJelly#3]
I'm trying to retrieve limb co-ordinates from the capture data, but it seems getUserData isn't sending the correct arguments to the OpenNI API.  Here's the error I get when running print k.getUserData() (once calibrated):

<code>CB [User 1]: New user
CB [User 1]: Pose detected
CB [User 1]: Calibration start
CB [User 1]: Calibration success!
Traceback (most recent call last):
<code>  File "scripts/python/kinect/skeleton-test-0.2.py", line 44, in <module>
<code>    print k.getUserData()
<code>  File "/usr/local/lib/python2.6/dist-packages/skeletonjelly.py", line 116, in getUserData
<code>    def getUserData(self, id = 1): return _skeletonjelly.Kinect_getUserData(self, id)
NotImplementedError: Wrong number of arguments for overloaded function 'Kinect_getUserData'.
<code>  Possible C/C++ prototypes are:
<code>    getUserData(Kinect &#42;,XnUserID)
<code>    getUserData(Kinect &#42;)

I've also tried getUserData(1) and getUserData(True), just in case it's my lack of experience in Python that's causing this, but it keeps returning the same error.

**Comment by benweissmann** [comment]
I'm having this issue too. It affects every method that needs an XnUserId, essentially making the python API completely broken for anython other than getCoM().

**Comment by vmg** [comment]
Hey, although I've dropped support for Python on the library (as you can read on the README file), here's some ideas to get this fixed: this is an issue with SWIG and the way it handles default arguments in Python. If you edit the C++ and remove the default argument for all the calls that have XNUserId, SWIG should generate the bindings properly.

Oh, and by the way, one of the reasons I dropped Python support is because SWIG sucks monkey dick. Cheers!
